/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_obnsoft_tjpemu_Native */

#ifndef _Included_com_obnsoft_tjpemu_Native
#define _Included_com_obnsoft_tjpemu_Native
#ifdef __cplusplus
extern "C" {
#endif
#undef com_obnsoft_tjpemu_Native_BUTTON_UP
#define com_obnsoft_tjpemu_Native_BUTTON_UP 0L
#undef com_obnsoft_tjpemu_Native_BUTTON_DOWN
#define com_obnsoft_tjpemu_Native_BUTTON_DOWN 1L
#undef com_obnsoft_tjpemu_Native_BUTTON_LEFT
#define com_obnsoft_tjpemu_Native_BUTTON_LEFT 2L
#undef com_obnsoft_tjpemu_Native_BUTTON_RIGHT
#define com_obnsoft_tjpemu_Native_BUTTON_RIGHT 3L
#undef com_obnsoft_tjpemu_Native_BUTTON_A
#define com_obnsoft_tjpemu_Native_BUTTON_A 4L
#undef com_obnsoft_tjpemu_Native_BUTTON_MAX
#define com_obnsoft_tjpemu_Native_BUTTON_MAX 5L
/*
 * Class:     com_obnsoft_tjpemu_Native
 * Method:    setup
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_obnsoft_tjpemu_Native_setup
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_obnsoft_tjpemu_Native
 * Method:    getEeprom
 * Signature: ([B)Z
 */
JNIEXPORT jboolean JNICALL Java_com_obnsoft_tjpemu_Native_getEeprom
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     com_obnsoft_tjpemu_Native
 * Method:    setEeprom
 * Signature: ([B)Z
 */
JNIEXPORT jboolean JNICALL Java_com_obnsoft_tjpemu_Native_setEeprom
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     com_obnsoft_tjpemu_Native
 * Method:    setRefreshTiming
 * Signature: (Z)Z
 */
JNIEXPORT jboolean JNICALL Java_com_obnsoft_tjpemu_Native_setRefreshTiming
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     com_obnsoft_tjpemu_Native
 * Method:    buttonEvent
 * Signature: (IZ)Z
 */
JNIEXPORT jboolean JNICALL Java_com_obnsoft_tjpemu_Native_buttonEvent
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     com_obnsoft_tjpemu_Native
 * Method:    loop
 * Signature: ([I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_obnsoft_tjpemu_Native_loop
  (JNIEnv *, jclass, jintArray);

/*
 * Class:     com_obnsoft_tjpemu_Native
 * Method:    getSoundBuffer
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_com_obnsoft_tjpemu_Native_getSoundBuffer
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     com_obnsoft_tjpemu_Native
 * Method:    teardown
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_obnsoft_tjpemu_Native_teardown
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
